import { query } from '../config/database';
import { AppError } from '../errors/AppError';
import * as notificationService from './notification.service';
import type { Role } from '../types/roles';
import type {
  WorkflowTriggerEvent,
  WorkflowActionType,
  WorkflowCondition,
  WorkflowLogStatus,
  WorkflowEventPayload,
  WorkflowLog,
  PaginatedWorkflowLogs,
  ListWorkflowLogsQuery,
} from '../types/workflow';

// ── Rule lookup ───────────────────────────────────────────────────────────────

interface WorkflowRuleRow {
  id: string;
  name: string;
  trigger_event: WorkflowTriggerEvent;
  condition: WorkflowCondition[] | null;
  actions: WorkflowActionType[];
}

async function fetchActiveRules(triggerEvent: WorkflowTriggerEvent): Promise<WorkflowRuleRow[]> {
  const { rows } = await query<WorkflowRuleRow>(
    `SELECT id, name, trigger_event, condition, actions::text[] AS actions
     FROM workflow_rules
     WHERE trigger_event = $1 AND is_active = TRUE AND deleted_at IS NULL
     ORDER BY created_at ASC`,
    [triggerEvent]
  );
  return rows;
}

function evaluateCondition(condition: WorkflowCondition[] | null, payload: WorkflowEventPayload): boolean {
  if (!condition || condition.length === 0) return true;
  return condition.every((c) => {
    const actual = payload[c.field];
    switch (c.operator) {
      case 'eq':
        return actual === c.value;
      case 'neq':
        return actual !== c.value;
      case 'gt':
        return typeof actual === 'number' && typeof c.value === 'number' && actual > c.value;
      case 'lt':
        return typeof actual === 'number' && typeof c.value === 'number' && actual < c.value;
      case 'gte':
        return typeof actual === 'number' && typeof c.value === 'number' && actual >= c.value;
      case 'lte':
        return typeof actual === 'number' && typeof c.value === 'number' && actual <= c.value;
      default:
        return false;
    }
  });
}

// ── Action registry ───────────────────────────────────────────────────────────
// Closed set of built-in handlers — a workflow_rules row can only select among
// these by name, never supply executable logic itself.

type ActionHandler = (payload: WorkflowEventPayload, actorId: string, triggerEvent: WorkflowTriggerEvent) => Promise<void>;

const ACTION_HANDLERS: Record<WorkflowActionType, ActionHandler> = {
  notify_students: async (payload, actorId) => {
    await notificationService.createNotification(actorId, 'faculty', {
      title: payload.title,
      message: payload.message,
      type: payload.notificationType,
      targetRole: 'student',
      departmentId: payload.departmentId,
      semester: payload.semester,
      isImportant: false,
    });
  },

  // Idempotent by construction: reuses the same (source_module, source_id)
  // uniqueness the Teaching Planner's calendar sync relies on, so a retry (or
  // a rule re-matching the same event) never creates a duplicate entry.
  create_calendar_event: async (payload, actorId, triggerEvent) => {
    if (!payload.sourceId || !payload.calendarDate) {
      throw new Error('create_calendar_event requires sourceId and calendarDate in the event payload');
    }
    const { rows: existing } = await query<{ id: string }>(
      `SELECT id FROM calendar_entries WHERE source_module = $1 AND source_id = $2 AND deleted_at IS NULL`,
      [triggerEvent, payload.sourceId]
    );
    if (existing[0]) return;

    await query(
      `INSERT INTO calendar_entries
         (title, description, event_type, start_date, visibility, source_module, source_id, department_id, semester, created_by)
       VALUES ($1, $2, $3, $4, 'department', $5, $6, $7, $8, $9)`,
      [
        payload.title,
        'Auto-generated by the Academic Workflow Engine',
        payload.calendarEventType ?? 'Other',
        payload.calendarDate,
        triggerEvent,
        payload.sourceId,
        payload.departmentId,
        payload.semester,
        actorId,
      ]
    );
  },

  log_only: async () => {
    /* intentional no-op — used when the triggering service already performs
       its own notification/calendar sync inline (see teachingPlan.service.ts) */
  },
};

// ── Logging ────────────────────────────────────────────────────────────────────

interface LogParams {
  triggerEvent: WorkflowTriggerEvent;
  ruleId: string | null;
  workflowName: string;
  action: WorkflowActionType | null;
  actorId: string;
  payload: WorkflowEventPayload;
  status: WorkflowLogStatus;
  errorMessage: string | null;
  retryCount: number;
}

async function logExecution(p: LogParams): Promise<void> {
  await query(
    `INSERT INTO workflow_logs
       (workflow_name, trigger_event, rule_id, action, actor_id, payload, status, error_message, retry_count)
     VALUES ($1,$2,$3,$4,$5,$6,$7,$8,$9)`,
    [p.workflowName, p.triggerEvent, p.ruleId, p.action, p.actorId, JSON.stringify(p.payload), p.status, p.errorMessage, p.retryCount]
  );
}

// ── Retry ──────────────────────────────────────────────────────────────────────
// One retry per action, scoped to the single failed action (not the whole
// rule) — actions that already logged 'success' are never re-run, so a retry
// can never create duplicate notifications/calendar entries from the same rule.

const MAX_ATTEMPTS = 2;

async function runActionWithRetry(
  rule: WorkflowRuleRow,
  action: WorkflowActionType,
  actorId: string,
  payload: WorkflowEventPayload
): Promise<void> {
  for (let attempt = 0; attempt < MAX_ATTEMPTS; attempt++) {
    try {
      await ACTION_HANDLERS[action](payload, actorId, rule.trigger_event);
      await logExecution({
        triggerEvent: rule.trigger_event,
        ruleId: rule.id,
        workflowName: rule.name,
        action,
        actorId,
        payload,
        status: 'success',
        errorMessage: null,
        retryCount: attempt,
      });
      return;
    } catch (err) {
      const message = err instanceof Error ? err.message : String(err);
      const isFinalAttempt = attempt === MAX_ATTEMPTS - 1;
      await logExecution({
        triggerEvent: rule.trigger_event,
        ruleId: rule.id,
        workflowName: rule.name,
        action,
        actorId,
        payload,
        status: isFinalAttempt ? 'failed' : 'retrying',
        errorMessage: message,
        retryCount: attempt,
      });
    }
  }
}

// ── Dispatch entry point ─────────────────────────────────────────────────────
// Never throws — the academic action that triggered this (e.g. "create
// assignment") must always succeed even if downstream workflow sync fails.

export async function emitWorkflowEvent(
  triggerEvent: WorkflowTriggerEvent,
  actorId: string,
  payload: WorkflowEventPayload
): Promise<void> {
  try {
    const rules = await fetchActiveRules(triggerEvent);
    const matched = rules.filter((r) => evaluateCondition(r.condition, payload));

    if (matched.length === 0) {
      await logExecution({
        triggerEvent,
        ruleId: null,
        workflowName: `${triggerEvent} (no active rule configured)`,
        action: null,
        actorId,
        payload,
        status: 'success',
        errorMessage: null,
        retryCount: 0,
      });
      return;
    }

    for (const rule of matched) {
      for (const action of rule.actions) {
        await runActionWithRetry(rule, action, actorId, payload);
      }
    }
  } catch (err) {
    console.error('[workflowEngine] dispatch failed unexpectedly', err);
  }
}

// ── Workflow log viewer (GET /faculty-operations/workflow-logs) ─────────────

interface WorkflowLogRow {
  id: string;
  workflow_name: string;
  trigger_event: WorkflowTriggerEvent;
  rule_id: string | null;
  action: WorkflowActionType | null;
  actor_id: string | null;
  actor_name: string | null;
  payload: Record<string, unknown> | null;
  status: WorkflowLogStatus;
  error_message: string | null;
  retry_count: number;
  executed_at: Date;
}

function toWorkflowLog(r: WorkflowLogRow): WorkflowLog {
  return {
    id: r.id,
    workflowName: r.workflow_name,
    triggerEvent: r.trigger_event,
    ruleId: r.rule_id,
    action: r.action,
    actorId: r.actor_id,
    actorName: r.actor_name,
    payload: r.payload,
    status: r.status,
    errorMessage: r.error_message,
    retryCount: r.retry_count,
    executedAt: r.executed_at,
  };
}

export async function getWorkflowLogs(
  userId: string,
  role: Role,
  filters: ListWorkflowLogsQuery
): Promise<PaginatedWorkflowLogs> {
  const conditions: string[] = ['1 = 1'];
  const params: unknown[] = [];
  const push = (cond: string, val: unknown) => {
    params.push(val);
    conditions.push(`${cond} $${params.length}`);
  };

  if (role === 'faculty') {
    const { rows } = await query<{ id: string; department_id: string; designation: string | null }>(
      'SELECT id, department_id, designation FROM faculty WHERE user_id = $1 AND deleted_at IS NULL',
      [userId]
    );
    if (!rows[0]) throw AppError.forbidden('No faculty profile is linked to this account');

    if (rows[0].designation === 'hod') {
      params.push(rows[0].department_id);
      conditions.push(`wl.actor_id IN (SELECT user_id FROM faculty WHERE department_id = $${params.length} AND deleted_at IS NULL)`);
    } else {
      push('wl.actor_id =', userId);
    }
  } else if (role !== 'admin') {
    throw AppError.forbidden('You do not have access to workflow logs');
  }

  if (filters.triggerEvent) push('wl.trigger_event =', filters.triggerEvent);
  if (filters.status) push('wl.status =', filters.status);
  if (filters.actorId) push('wl.actor_id =', filters.actorId);

  params.push(filters.limit, (filters.page - 1) * filters.limit);
  const limitN = params.length - 1;
  const offsetN = params.length;

  const { rows } = await query<WorkflowLogRow & { total_count: string }>(
    `SELECT wl.id, wl.workflow_name, wl.trigger_event, wl.rule_id, wl.action, wl.actor_id,
       u.full_name AS actor_name, wl.payload, wl.status, wl.error_message, wl.retry_count, wl.executed_at,
       COUNT(*) OVER()::text AS total_count
     FROM workflow_logs wl
     LEFT JOIN users u ON u.id = wl.actor_id
     WHERE ${conditions.join(' AND ')}
     ORDER BY wl.executed_at DESC
     LIMIT $${limitN} OFFSET $${offsetN}`,
    params
  );

  const total = rows[0] ? Number(rows[0].total_count) : 0;
  return {
    logs: rows.map(toWorkflowLog),
    total,
    page: filters.page,
    limit: filters.limit,
    totalPages: Math.ceil(total / filters.limit),
  };
}
